app1/urls.py
from django.conf.urls import url
from app1.views import consultant
from app1.views import teacher

urlpatterns = [
    # 公户
    url(r'^customer_list/', consultant.CustomerList.as_view(), name='customer_list'),
    # 私户
    url(r'^my_customer/', consultant.CustomerList.as_view(), name='my_customer'),

    url(r'^user_list/', consultant.user_list, name='user_list'),

    # 添加
    # url(r'^customer_add/', views.customer_add, name='customer_add'),
    url(r'^customer_add/', consultant.customer_change, name='customer_add'),
    # 编辑
    # url(r'^customer_edit/(\d+)/', views.customer_edit, name='customer_edit'),
    url(r'^customer_edit/(\d+)/', consultant.customer_change, name='customer_edit'),

    # 展示跟进记录表
    url(r'^consult_list/(0)/', consultant.ConsultList.as_view(), name='all_consult_list'),
    url(r'^consult_list/(?P<customer_id>\d+)/', consultant.ConsultList.as_view(), name='consult_list'),
    url(r'^consult_add/', consultant.consult_add, name='consult_add'),
    url(r'^consult_edit/(\d+)', consultant.consult_edit, name='consult_edit'),

    # 展示报名记录
    url(r'^enrollment_list/(?P<customer_id>\d+)/', consultant.EnrollmentList.as_view(), name='enrollment_list'),
    # 添加报名记录
    url(r'^enrollment_add/(?P<customer_id>\d+)', consultant.enrollment, name='enrollment_add'),
    url(r'^enrollment_edit/(?P<record_id>\d+)', consultant.enrollment, name='enrollment_edit'),

    # 展示班级
    url(r'^class_list/', teacher.ClassList.as_view(), name='class_list'),
    # 新增班级
    url(r'^class_add/', teacher.classes, name='class_add'),
    # 编辑班级
    url(r'^class_edit/(\d+)', teacher.classes, name='class_edit'),

    # 展示课程记录
    url(r'^course_record_list/(?P<class_id>\d+)', teacher.CourseRecordList.as_view(), name='course_record_list'),
    url(r'^course_record_add/(?P<class_id>\d+)', teacher.course_record, name='course_record_add'),
    url(r'^course_record_edit/(?P<course_request_id>\d+)', teacher.course_record, name='course_record_edit'),

    # 展示学习记录
    url(r'^study_record_list/(?P<course_record_id>\d+)/', teacher.study_record, name='study_record_list'),
]

rbec/urls.py
from django.conf.urls import url
from rbec import views
from app1.views import account

urlpatterns = [
    url(r'^role/list/$', views.role_list, name='role_list'),
    url(r'^role/add/$', views.role, name='role_add'),
    url(r'^role/edit/(\d+)$', views.role, name='role_edit'),
    url(r'^role/del/(\d+)$', views.role_del, name='role_del'),

    url(r'^menu/list/$', views.menu_list, name='menu_list'),
    url(r'^menu/add/$', views.menu, name='menu_add'),
    url(r'^menu/edit/(\d+)$', views.menu, name='menu_edit'),
    url(r'^menu/del/(\d+)$', views.menu_del, name='menu_del'),

    url(r'^permission/edit/(\d+)$', views.permission, name='permission_edit'),
    url(r'^permission/add/$', views.permission, name='permission_add'),
    url(r'^permission/del/(\d+)$', views.permission_del, name='permission_del'),

    url(r'^multi/permissions/$', views.multi_permissions, name='multi_permissions'),
    url(r'^distribute/permissions/$', views.distribute_permissions, name='distribute_permissions')

]

untitled2/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from app1.views import account
from app1.views import consultant

urlpatterns = [
    url(r'^admin/', admin.site.urls, name='admin'),
    url(r'^login/', account.login, name='login'),
    url(r'^index', consultant.index, name='index'),
    url(r'^reg/', account.reg, name='reg'),
    url(r'^logout/', account.logout, name='logout'),
    url(r'app1/', include('app1.urls')),
    url(r'^rbec/', include('rbec.urls', namespace='rbec')),

]
"""
    include: 让路径变为 app1/(urls)
    """

rbec/models.py
from django.db import models

""""
verbose_name_plural:
verbose_name: 
blank: 
"""


class Menu(models.Model):
    """
    一级菜单
    """
    title = models.CharField(max_length=32)
    icon = models.CharField(max_length=64, null=True)
    weight = models.IntegerField(default=1)

    def __str__(self):
        return self.title


class Permission(models.Model):
    """
    权限表
    BooleanField: 返回True or False
    """
    url = models.CharField(max_length=108, verbose_name='权限')
    title = models.CharField(max_length=64, verbose_name='标题')
    menu = models.ForeignKey('Menu', null=True, blank=True)
    parent = models.ForeignKey('self', null=True, blank=True)  # 自关联
    name = models.CharField(max_length=108, verbose_name='URL_别名')

    # is_menu = modlels.BooleanField(default=False, verbose_name='是否是菜单')
    # icon = models.CharField(max_length=64, null=True, blank=True, verbose_name='图标')

    class Meta:
        verbose_name_plural = '权限'
        verbose_name = '权限'

    def __str__(self):
        return self.title


class Role(models.Model):
    """
    角色表
    """
    name = models.CharField(max_length=32, verbose_name='名字')
    permissions = models.ManyToManyField('Permission', verbose_name='角色拥有的权限', blank=True)

    def __str__(self):
        return self.name


class User(models.Model):
    """
    用户表
    """
    # name = models.CharField(max_length=32, verbose_name='名称')
    # password = models.CharField(max_length=32, verbose_name='密码')
    roles = models.ManyToManyField(Role, verbose_name='y用户拥有的角色', blank=True)

    # def __str__(self):
    #     return self.name
    class Meta:
        abstract = True  # 数据库迁移的时候不会生成表, 基类用作继承

rbec/service/routes.py
from django.conf import settings
from django.utils.module_loading import import_string
from django.urls import RegexURLResolver, RegexURLPattern
from collections import OrderedDict
from importlib import import_module


def recursion_urls(pre_namespace, pre_url, urlpatterns, url_ordered_dict):
    for item in urlpatterns:
        if isinstance(item, RegexURLResolver):
            if pre_namespace:
                if item.namespace:
                    namespace = "%s:%s" % (pre_namespace, item.namespace,)
                else:
                    namespace = pre_namespace
            else:
                if item.namespace:
                    namespace = item.namespace
                else:
                    namespace = None

            recursion_urls(namespace, pre_url + item.regex.pattern, item.url_patterns, url_ordered_dict)
        else:

            if pre_namespace:
                name = "%s:%s" % (pre_namespace, item.name,)
            else:
                name = item.name
            if not item.name:
                raise Exception('URL路由中必须设置name属性')
            # /^rbac/^role/list/$'
            # /rbac/role/list/
            url = pre_url + item._regex
            url_ordered_dict[name] = {'name': name, 'url': url.replace('^', '').replace('$', '')}


def get_all_url_dict(ignore_namespace_list=None):
    """
    获取路由中所有的URL和别名
    :return:
    """
    ignore_list = ignore_namespace_list or []
    url_ordered_dict = OrderedDict()

    md = import_module(settings.ROOT_URLCONF)
    urlpatterns = []

    for item in md.urlpatterns:
        if isinstance(item, RegexURLResolver) and item.namespace in ignore_list:
            continue
        urlpatterns.append(item)
    recursion_urls(None, "/", urlpatterns, url_ordered_dict)
    return url_ordered_dict

rbec/views.py
from django.shortcuts import render, reverse, redirect, HttpResponse
from rbec.forms import RoleForm, MenuForm, PermissionForm, MultiPermissionForm
from rbec import models
from django.db.models import Q
from collections import OrderedDict
from app1.models import UserProfile


# Create your views here.
# 展示角色
def role_list(request):
    all_role = models.Role.objects.all()
    return render(request, 'rbac/role_list.html', {'all_role': all_role})


def role(request, edit_id=None):
    obj = models.Role.objects.filter(pk=edit_id).first()
    form_obj = RoleForm(instance=obj)
    if request.method == 'POST':
        form_obj = RoleForm(request.POST, instance=obj)
        if form_obj.is_valid():
            form_obj.save()
            return redirect(reverse('role_list'))
    return render(request, 'rbac/role_form.html', {'form_obj': form_obj})


def role_del(request, del_id):
    models.Role.objects.filter(pk=del_id).delete()
    return redirect(reverse('role_list'))


def menu_list(request, ):
    mid = request.GET.get('mid')
    all_menus = models.Menu.objects.all()

    if mid:
        all_permissions = models.Permission.objects.filter(Q(menu_id=mid) | Q(parent__menu_id=mid))  # 和menu 表一一对应

    else:
        all_permissions = models.Permission.objects.all()

    permission_query = all_permissions.values()
    print('permission_query', permission_query)
    permission_dict = OrderedDict()

    # print(permission_query)
    for item in permission_query:
        if item.get('menu_id'):
            permission_dict[item['id']] = item
            item['children'] = []

    for item in permission_query:
        pid = item.get('parent_id')
        if pid:
            permission_dict[pid]['children'].append(item)

    print(permission_dict)
    return render(request, 'rbac/menu_list.html',
                  {'all_menus': all_menus, 'all_permissions': permission_dict, 'mid': mid})


def menu(request, edit_id=None):
    obj = models.Menu.objects.filter(pk=edit_id).first()
    form_obj = MenuForm(instance=obj)
    if request.method == 'POST':
        form_obj = MenuForm(request.POST, instance=obj)
        if form_obj.is_valid():
            form_obj.save()
            return redirect(reverse('rbec:menu_list'))
    return render(request, 'rbac/menu_form.html', {'form_obj': form_obj})


def menu_del(request, del_id):
    models.Menu.objects.filter(pk=del_id).delete()
    return redirect(reverse('rbec:menu_list'))


def permission(request, edit_id=None):
    obj = models.Permission.objects.filter(pk=edit_id).first()
    form_obj = PermissionForm(instance=obj)
    if request.method == 'POST':
        form_obj = PermissionForm(request.POST, instance=obj)
        if form_obj.is_valid():
            form_obj.save()
            return redirect(reverse('rbec:menu_list'))
    return render(request, 'rbac/menu_form.html', {'form_obj': form_obj})


def permission_del(request, del_id):
    models.Permission.objects.filter(pk=del_id).delete()
    return redirect(reverse('rbec: menu_list'))


from django.forms import modelformset_factory, formset_factory
from rbec.service.routes import get_all_url_dict


def multi_permissions(request):
    post_type = request.GET.get('type')
    # 用做编辑和删除
    FormSet = modelformset_factory(models.Permission, MultiPermissionForm, extra=0)
    # 用做新增
    AddFormSet = formset_factory(MultiPermissionForm, extra=0)
    # 数据库中所有的权限信息
    permissions = models.Permission.objects.all()
    # 项目路由系统中的所有URL
    router_dict = get_all_url_dict(ignore_namespace_list=['admin'])

    # 数据库中权限的所有的别名
    permissions_name_set = set([i.name for i in permissions])
    # 路由系统中所有的别名
    router_name_set = set(router_dict.keys())

    # 带插入到数据库中权限的别名
    add_name_set = router_name_set - permissions_name_set
    add_formset = AddFormSet(initial=[row for name, row in router_dict.items() if name in add_name_set])

    if request.method == 'POST' and post_type == 'add':
        add_formset = AddFormSet(request.POST)
        if add_formset.is_valid():
            permission_obj_list = [models.Permission(**i) for i in add_formset.cleaned_data]

            query_list = models.Permission.objects.bulk_create(permission_obj_list)

            for i in query_list:
                permissions_name_set.add(i.name)
            add_formset = AddFormSet()

    del_name_set = permissions_name_set - router_name_set
    del_formset = FormSet(queryset=models.Permission.objects.filter(name__in=del_name_set))

    update_name_set = permissions_name_set & router_name_set
    update_formset = FormSet(queryset=models.Permission.objects.filter(name__in=update_name_set))

    if request.method == 'POST' and post_type == 'update':
        update_formset = FormSet(request.POST)
        if update_formset.is_valid():
            update_formset.save()
            update_formset = FormSet(queryset=models.Permission.objects.filter(name__in=update_name_set))

    return render(
        request,
        'rbac/multi_permissions.html',
        {
            'del_formset': del_formset,
            'update_formset': update_formset,
            'add_formset': add_formset,
        }
    )


def distribute_permissions(request):
    """
    分配权限
    :param request:
    :return:
    """
    uid = request.GET.get('uid')
    rid = request.GET.get('rid')

    if request.method == 'POST' and request.POST.get('postType') == 'role':
        user = UserProfile.objects.filter(id=uid).first()
        if not user:
            return HttpResponse('用户不存在')
        user.roles.set(request.POST.getlist('roles'))

    if request.method == 'POST' and request.POST.get('postType') == 'permission' and rid:
        role = models.Role.objects.filter(id=rid).first()
        if not role:
            return HttpResponse('角色不存在')
        role.permissions.set(request.POST.getlist('permissions'))

    # 获取所有的用户
    user_list = UserProfile.objects.all()

    # 当前用户所拥有的角色
    user_has_roles = UserProfile.objects.filter(id=uid).values('id', 'roles')

    user_has_roles_dict = {item['roles']: None for item in user_has_roles}
    """
    user_has_roles_dict = { 角色的id：None  }
    """
    # 所有的角色
    role_list = models.Role.objects.all()

    if rid:
        role_has_permissions = models.Role.objects.filter(id=rid).values('id', 'permissions')
    elif uid and not rid:
        user = UserProfile.objects.filter(id=uid).first()
        if not user:
            return HttpResponse('用户不存在')
        role_has_permissions = user.roles.values('id', 'permissions')
    else:
        role_has_permissions = []

    role_has_permissions_dict = {item['permissions']: None for item in role_has_permissions}

    """"
    role_has_permissions_dict = { 权限的id ：None  }
    """

    all_menu_list = []
    """
    all_menu_list  = [
        { 'id', 'title'， ‘children' : [
            { 'id', 'title', 'menu_id' , 'children': [
            {'id', 'title', 'parent_id'}
        ] }
           ]   },
        {'id': None, 'title': '其他', 'children': [
         {'id', 'title', 'parent_id'}
        ]}
    ]
    """
    queryset = models.Menu.objects.values('id', 'title')
    menu_dict = {}

    """
    menu_dict = { 一级菜单的id ： { 'id', 'title'，
    ‘children' : [
        { 'id', 'title', 'menu_id' , 'children': [
            {'id', 'title', 'parent_id'}
        ] }
     ]   },
             None : {'id': None, 'title': '其他', 'children': [
               {'id', 'title', 'parent_id'}
             ]}

    }
    """

    for item in queryset:
        item['children'] = []  # 放二级菜单  父权限
        menu_dict[item['id']] = item
        all_menu_list.append(item)

    other = {'id': None, 'title': '其他', 'children': []}
    all_menu_list.append(other)
    menu_dict[None] = other
    # 二级菜单  父权限
    root_permission = models.Permission.objects.filter(menu__isnull=False).values('id', 'title', 'menu_id')

    root_permission_dict = {}

    """
    root_permission_dict =  { 父权限的id: { 'id', 'title', 'menu_id' , 'children': [
        {'id', 'title', 'parent_id'}
    ] }  }
    """

    for per in root_permission:
        per['children'] = []  # 放子权限
        nid = per['id']
        menu_id = per['menu_id']
        root_permission_dict[nid] = per
        menu_dict[menu_id]['children'].append(per)

    # 除了父权限的其他的权限
    node_permission = models.Permission.objects.filter(menu__isnull=True).values('id', 'title', 'parent_id')

    for per in node_permission:
        pid = per['parent_id']
        if not pid:
            menu_dict[None]['children'].append(per)
            continue
        root_permission_dict[pid]['children'].append(per)

    return render(
        request,
        'rbac/distribute_permissions.html',
        {
            'user_list': user_list,
            'role_list': role_list,
            'user_has_roles_dict': user_has_roles_dict,
            'role_has_permissions_dict': role_has_permissions_dict,
            'all_menu_list': all_menu_list,
            'uid': uid,
            'rid': rid
        }
    )

rbec/templates/rbac/breadctumb.html
<ol class="breadcrumb no-radius no-margin" style="border-bottom: 1px solid #ddd;">

                {% for li in breadcrumb_list %}

        {% if forloop.last %}
            <li class="active">{{ li.title }}</li>

        {% else %}
            <li><a href="{{ li.url }}"> {{ li.title }}</a></li>
        {% endif %}

    {% endfor %}

            </ol>

rbec/templates/rbac/menu.html
{#<div class="static-menu">#}
{#    {% for item in menu_list %}#}
{#                <a href="{{ item.url }}" class="{{ i.class }}">#}
{#                    <span class="icon-wrap"><i class="fa {{ item.icon }}"></i></span> {{ item.title }}</a>#}
{#            {% endfor %}#}
{#</div>#}

<div class="multi-menu">
    {% for item in menu_list %}
        <div class="item">
            <div class="title"><i class="fa {{ item.icon }}"></i> {{ item.title }} </div>
            <div class="body {{ item.class }}">

                {% for child in item.children %}
                    <a href="{{ child.url }}" class="{{ child.class }}">{{ child.title }}</a>
                {% endfor %}
            </div>
        </div>
    {% endfor %}


</div>

rbec/templates/rbac/menu_form.html
{% extends 'layout.html' %}

{% block css %}
    <style>
        ul {
            list-style-type: none;
            padding: 0;
        }

        ul li {
            float: left;
            padding: 10px;
            padding-left: 0;
            width: 80px;
        }

        .icon-area ul li i {
            font-size: 18px;
            margin-left: 5px;
            color: #6d6565;
        }


    </style>
{% endblock %}

{% block content %}

    <div style="margin-top: 70px">
        <form class="form-horizontal icon-area" novalidate action="" method="post" >
            {% csrf_token %}
            {% for field in form_obj %}

                <div class="form-group {% if field.errors %} has-error {% endif %}  ">

                    <label for="{{ field.id_for_label }}" class="col-sm-2 control-label">{{ field.label }}</label>
                    <div class="col-sm-6">
                        {{ field }}
                        <span class="help-block"> {{ field.errors.0 }} </span>
                    </div>
                </div>
            {% endfor %}


            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <button type="submit" class="btn btn-default">提交</button>
                </div>
            </div>

        </form>
    </div>

{% endblock %}

rbec/templates/rbac/menu_list.html
{% extends 'layout.html' %}

{% block css %}
    <style>
        .permission-area tr.root {
            background-color: #b1d6ff;
        }

        .menu-body tr.active {
            background-color: #f1f7fd;
            border-left: 3px solid #fdc00f;
        }


    </style>
{% endblock %}

{% block content %}

    <div style="margin-top: 20px">
        <div class="col-sm-3">
            <div class="panel panel-default">
                <div class="panel-heading"><i class="fa fa-book"></i> 菜单管理
                    <a href="{% url 'rbec:menu_add' %}" class="btn btn-sm btn-success pull-right"
                       style="padding: 2px 7px;margin-top: -2px"> <i
                            class="fa fa-plus"></i> 添加</a>
                </div>

                <table class="table  table-hover">
                    <thead>
                    <tr>
                        <th>名称</th>
                        <th>图标</th>
                        <th>操作</th>
                    </tr>
                    </thead>
                    <tbody class="menu-body">
                    {% for menu in all_menus %}
                        <tr class="{% if mid == menu.id|safe %}active{% endif %}">

                            <td><a href="?mid={{ menu.pk }}">{{ menu.title }}</a></td>
                            <td><i class="fa {{ menu.icon }}"></i></td>
                            <td>
                                <a href="{% url 'rbec:menu_edit' menu.pk %}"> <i class="fa fa-pencil-square-o"></i> </a>
                                <a href="{% url 'rbec:menu_del'  menu.pk %}" style="color: red"> <i
                                        class="fa fa-trash-o"></i> </a>

                            </td>
                        </tr>

                    {% endfor %}


                    </tbody>

                </table>

            </div>
        </div>
        <div class="col-sm-9">
            <div class="panel panel-default">
                <div class="panel-heading"><i class="fa fa-cubes"></i> 权限管理
                    <a href="{% url 'rbec:multi_permissions' %}" class="btn btn-sm btn-primary pull-right "
                       style="padding: 2px 7px;margin-top: -2px">批量操作</a>
                    <a href="{% url 'rbec:permission_add' %}" class="btn btn-sm btn-success pull-right"
                       style="padding: 2px 7px;margin-top: -2px">添加</a>
                </div>
                <table class="table  table-hover">
                    <thead>
                    <tr>
                        <th>名称</th>
                        <th>URL</th>
                        <th>URL别名</th>
                        <th>操作</th>
                    </tr>
                    </thead>
                    <tbody class="permission-area">
                    {% for p_permission in all_permissions.values %}
                        <tr class="root" id="{{ p_permission.id }}">

                            <td class="title">
                                <i class="fa fa-caret-down"></i>
                                {{ p_permission.title }}
                            </td>
                            <td>{{ p_permission.url }}</td>
                            <td>{{ p_permission.name }}</td>
                            <td>
                                <a href="{% url 'rbec:permission_edit' p_permission.id %}"> <i
                                        class="fa fa-pencil-square-o"></i> </a>
                                <a href="{% url 'rbec:permission_del'%}" style="color: red"> <i
                                        class="fa fa-trash-o"></i> </a>

                            </td>
                        </tr>

                        {% for c_permission in p_permission.children %}
                            <tr pid="{{ p_permission.id }}">

                                <td>{{ c_permission.title }}</td>
                                <td>{{ c_permission.url }}</td>
                                <td>{{ c_permission.name }}</td>
                                <td>
                                    <a href=" "> <i class="fa fa-pencil-square-o"></i> </a>
                                    <a href="" style="color: red"> <i
                                            class="fa fa-trash-o"></i> </a>

                                </td>
                            </tr>

                        {% endfor %}


                    {% endfor %}


                    </tbody>

                </table>
            </div>
        </div>

    </div>

{% endblock %}

{% block js %}
    <script>


        $('.permission-area').on('click', '.root .title', function () {
            var caret = $(this).find('i');
            var id = $(this).parent().attr('id');
            if (caret.hasClass('fa-caret-right')) {
                caret.removeClass('fa-caret-right').addClass('fa-caret-down');
                $(this).parent().nextAll('tr[pid="' + id + '"]').removeClass('hide');
            } else {
                caret.removeClass('fa-caret-down').addClass('fa-caret-right');
                $(this).parent().nextAll('tr[pid="' + id + '"]').addClass('hide');

            }
        })


    </script>
{% endblock %}

rbec/templates/rbac/multi_permissions.html
{% extends 'layout.html' %}

{% block content %}
    <div class="luffy-container">
        <form method="post" action="?type=add">
            {% csrf_token %}
            {{ add_formset.management_form }}
            <div class="panel panel-default">
                <!-- Default panel contents -->
                <div class="panel-heading">
                    <i class="fa fa-binoculars" aria-hidden="true"></i> 待新建权限列表
                    <button class="pull-right btn btn-primary btn-xs" style="padding: 2px 8px;margin: -3px;">
                        <i class="fa fa-save" aria-hidden="true"></i>
                        新建
                    </button>
                </div>
                <div class="panel-body" style="color: #9d9d9d;">
                    注意：路由系统中自动发现且数据库中不存在的路由。
                </div>

                <table class="table table-bordered">
                    <thead>
                    <tr>
                        <th>序号</th>
                        <th>名称</th>
                        <th>URL</th>
                        <th>别名</th>
                        <th>父权限</th>
                        <th>所属菜单</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for form in add_formset %}

                        <tr>
                            <td style="vertical-align: middle;">{{ forloop.counter }}</td>
                            <td>{{ form.title }} <span>{{ form.title.errors.0 }}</span></td>
                            <td>{{ form.url }}</td>
                            <td>{{ form.name }}</td>
                            <td>{{ form.parent }}</td>
                            <td>{{ form.menu }}</td>

                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </form>

        <div class="panel panel-default">
            <!-- Default panel contents -->
            <div class="panel-heading">
                <i class="fa fa-th-list" aria-hidden="true"></i> 待删除权限列表
            </div>
            <div class="panel-body" style="color: #9d9d9d;">
                注意：数据库中存在，但路由系统中不存在的路由。
            </div>

            <table class="table table-bordered">
                <thead>
                <tr>
                    <th>序号</th>
                    <th>名称</th>
                    <th>URL</th>
                    <th>别名</th>
                    <th>父权限</th>
                    <th>所属菜单</th>
                    <th>操作</th>
                </tr>
                </thead>
                <tbody>
                {% for form in del_formset %}

                    <tr>
                        {{ form.id }}

                        <td style="vertical-align: middle;">{{ forloop.counter }}</td>
                        <td>{{ form.title }} <span>{{ form.title.errors.0 }}</span></td>
                        <td>{{ form.url }}</td>
                        <td>{{ form.name }}</td>
                        <td>{{ form.parent }}</td>
                        <td>{{ form.menu }}</td>
                        <td>
                            <a href="{% url 'rbec:permission_del' form.id.value %}" style="color:#d9534f;">
                                <i class="fa fa-trash-o" aria-hidden="true"></i>
                            </a>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>

        <form method="post" action="?type=update">
            {% csrf_token %}
            {{ update_formset.management_form }}
            <div class="panel panel-default">
                <!-- Default panel contents -->
                <div class="panel-heading">
                    <i class="fa fa-sitemap" aria-hidden="true"></i> 待更新权限列表
                    <button class="pull-right btn btn-primary btn-xs" style="padding: 2px 8px;margin: -3px;">
                        <i class="fa fa-save" aria-hidden="true"></i>
                        更新
                    </button>
                </div>
                <div class="panel-body" style="color: #9d9d9d;">
                    注意：数据库和路由系统都存在的路由。
                </div>

                <table class="table table-bordered">
                    <thead>
                    <tr>
                        <th>序号</th>
                        <th>名称</th>
                        <th>URL</th>
                        <th>别名</th>
                        <th>父权限</th>
                        <th>所属菜单</th>
                        <th>操作</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for form in update_formset %}
                        <tr>
                            {{ form.id }}

                            <td style="vertical-align: middle;">{{ forloop.counter }}</td>
                            <td>{{ form.title }} <span>{{ form.title.errors.0 }}</span></td>
                            <td>{{ form.url }}</td>
                            <td>{{ form.name }}</td>
                            <td>{{ form.parent }}</td>
                            <td>{{ form.menu }}</td>
                            <td>
                                <a href="{% url 'rbec:permission_del' form.id.value %}" style="color:#d9534f;">
                                    <i class="fa fa-trash-o" aria-hidden="true"></i>
                                </a>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </form>
    </div>
{% endblock %}

rbec/templates/rbac/role_form.html
{% extends 'layout.html' %}


{% block content %}

    <div style="margin-top: 70px">
        <form class="form-horizontal" novalidate action="" method="post">
            {% csrf_token %}
            {% for field in form_obj %}

                <div class="form-group {% if field.errors %} has-error {% endif %}  ">

                    <label for="{{ field.id_for_label }}" class="col-sm-2 control-label">{{ field.label }}</label>
                    <div class="col-sm-7">
                        {{ field }}
                        <span class="help-block"> {{ field.errors.0 }} </span>
                    </div>
                </div>
            {% endfor %}


            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <button type="submit" class="btn btn-default">提交</button>
                </div>
            </div>

        </form>
    </div>

{% endblock %}

rbec/templates/rbac/role_list.html
{% extends 'layout.html' %}

{% block content %}
    <div style="margin: 20px"></div>
     <a href="{% url 'rbec:role_add' %}" class="btn btn-primary">添加</a>
    <table class="table table-bordered table-hover">
        <thead>
            <tr>
                <th>序号</th>
                <th>名称</th>
                <th>操作</th>
            </tr>
        </thead>
        <tbody>
        {% for role in all_role %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td>{{ role.name }}</td>
                <td>
                    <a href="{% url 'rbec:role_edit' role.pk %}"> <i class="fa fa-pencil-square-o"></i> </a>
                    <a href="{% url 'rbec:role_del' role.pk %}" style="color: red"> <i class="fa fa-trash-o"></i> </a>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

{% endblock %}