app1/urls.py
from django.conf.urls import url
from app1.views import consultant
from app1.views import teacher

urlpatterns = [
    # 公户
    url(r'^customer_list/', consultant.CustomerList.as_view(), name='customer_list'),
    # 私户
    url(r'^my_customer/', consultant.CustomerList.as_view(), name='my_customer'),

    url(r'^user_list/', consultant.user_list, name='user_list'),

    # 添加
    # url(r'^customer_add/', views.customer_add, name='customer_add'),
    url(r'^customer_add/', consultant.customer_change, name='customer_add'),
    # 编辑
    # url(r'^customer_edit/(\d+)/', views.customer_edit, name='customer_edit'),
    url(r'^customer_edit/(\d+)/', consultant.customer_change, name='customer_edit'),

    # 展示跟进记录表
    url(r'^consult_list/(0)/', consultant.ConsultList.as_view(), name='all_consult_list'),
    url(r'^consult_list/(?P<customer_id>\d+)/', consultant.ConsultList.as_view(), name='consult_list'),
    url(r'^consult_add/', consultant.consult_add, name='consult_add'),
    url(r'^consult_edit/(\d+)', consultant.consult_edit, name='consult_edit'),

    # 展示报名记录
    url(r'^enrollment_list/(?P<customer_id>\d+)/', consultant.EnrollmentList.as_view(), name='enrollment_list'),
    # 添加报名记录
    url(r'^enrollment_add/(?P<customer_id>\d+)', consultant.enrollment, name='enrollment_add'),
    url(r'^enrollment_edit/(?P<record_id>\d+)', consultant.enrollment, name='enrollment_edit'),

    # 展示班级
    url(r'^class_list/', teacher.ClassList.as_view(), name='class_list'),
    # 新增班级
    url(r'^class_add/', teacher.classes, name='class_add'),
    # 编辑班级
    url(r'^class_edit/(\d+)', teacher.classes, name='class_edit'),

    # 展示课程记录
    url(r'^course_record_list/(?P<class_id>\d+)', teacher.CourseRecordList.as_view(), name='course_record_list'),
    url(r'^course_record_add/(?P<class_id>\d+)', teacher.course_record, name='course_record_add'),
    url(r'^course_record_edit/(?P<course_request_id>\d+)', teacher.course_record, name='course_record_edit'),

    # 展示学习记录
    url(r'^study_record_list/(?P<course_record_id>\d+)/', teacher.study_record, name='study_record_list'),
]

untitled2/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from app1.views import account
from app1.views import consultant

urlpatterns = [
    url(r'^admin/', admin.site.urls, name='admin'),
    url(r'^login/', account.login, name='login'),
    url(r'^index', consultant.index, name='index'),
    url(r'^reg/', account.reg, name='reg'),
    url(r'^logout/', account.logout, name='logout'),
    url(r'app1/', include('app1.urls')),
    url(r'^rbec/', include('rbec.urls', namespace='rbec')),

]
"""
    include: 让路径变为 app1/(urls)
    """

app1/models.py
from django.db import models
from multiselectfield import MultiSelectField
from rbec.models import User

course_choices = (('Linux', 'Linux中高级'),
                  ('PythonFullStack', 'Python高级全栈开发'),)

class_type_choices = (('fulltime', '脱产班',),
                      ('online', '网络班'),
                      ('weekend', '周末班',),)

source_type = (('qq', "qq群"),
               ('referral', "内部转介绍"),
               ('website', "官方网站"),
               ('baidu_ads', "百度推广"),
               ('office_direct', "直接上门"),
               ('WoM', "口碑"),
               ('public_class', "公开课"),
               ('website_luffy', "路飞官网"),
               ('others', "其它"),)

enroll_status_choices = (('signed', "已报名"),
                         ('unregistered', "未报名"),
                         ('studying', '学习中'),
                         ('paid_in_full', "学费已交齐"))

seek_status_choices = (('A', '近期无报名计划'), ('B', '1个月内报名'), ('C', '2周内报名'), ('D', '1周内报名'),
                       ('E', '定金'), ('F', '到班'), ('G', '全款'), ('H', '无效'),)
pay_type_choices = (('deposit', "订金/报名费"),
                    ('tuition', "学费"),
                    ('transfer', "转班"),
                    ('dropout', "退学"),
                    ('refund', "退款"),)

attendance_choices = (('checked', "已签到"),
                      ('vacate', "请假"),
                      ('late', "迟到"),
                      ('absence', "缺勤"),
                      ('leave_early', "早退"),)

score_choices = ((100, 'A+'),
                 (90, 'A'),
                 (85, 'B+'),
                 (80, 'B'),
                 (70, 'B-'),
                 (60, 'C+'),
                 (50, 'C'),
                 (40, 'C-'),
                 (0, ' D'),
                 (-1, 'N/A'),
                 (-100, 'COPY'),
                 (-1000, 'FAIL'),)


class Department(models.Model):
    """
    部门表
    """
    name = models.CharField(max_length=32, verbose_name="部门名称", )
    count = models.IntegerField(verbose_name="人数", default=0)

    def __str__(self):
        return self.name
    # class Meta:
    #     db_table = 'xxx'   # 表名


class UserProfile(User, models.Model):
    """
    用户表
    """
    username = models.EmailField(max_length=255, unique=True, )
    password = models.CharField(max_length=128)
    name = models.CharField('名字', max_length=32)
    department = models.ForeignKey('Department', default=None, blank=True, null=True)
    mobile = models.CharField('手机', max_length=32, default=None, blank=True, null=True)
    memo = models.TextField('备注', blank=True, null=True, default=None)
    date_joined = models.DateTimeField(auto_now_add=True)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.name


class Customer(models.Model):
    """
    客户表
    """
    qq = models.CharField('QQ', max_length=64, unique=True, help_text='QQ号必须唯一')
    qq_name = models.CharField('QQ昵称', max_length=64, blank=True, null=True)
    name = models.CharField('姓名', max_length=32, blank=True, null=True, help_text='学员报名后，请改为真实姓名')
    sex_type = (('male', '男'), ('female', '女'))
    sex = models.CharField("性别", choices=sex_type, max_length=16, default='male', blank=True, null=True)
    birthday = models.DateField('出生日期', default=None, help_text="格式yyyy-mm-dd", blank=True, null=True)
    phone = models.BigIntegerField('手机号', blank=True, null=True)
    source = models.CharField('客户来源', max_length=64, choices=source_type, default='qq')
    introduce_from = models.ForeignKey('self', verbose_name="转介绍自学员", blank=True, null=True)
    course = MultiSelectField("咨询课程", choices=course_choices)
    class_type = models.CharField("班级类型", max_length=64, choices=class_type_choices, default='fulltime')
    customer_note = models.TextField("客户备注", blank=True, null=True, )
    status = models.CharField("状态", choices=enroll_status_choices, max_length=64, default="unregistered",
                              help_text="选择客户此时的状态")
    network_consult_note = models.TextField(blank=True, null=True, verbose_name='网络咨询师咨询内容')
    date = models.DateTimeField("咨询日期", auto_now_add=True)
    last_consult_date = models.DateField("最后跟进日期", auto_now_add=True)
    next_date = models.DateField("预计再次跟进时间", blank=True, null=True)
    network_consultant = models.ForeignKey('UserProfile', blank=True, null=True, verbose_name='咨询师',
                                           related_name='network_consultant')
    consultant = models.ForeignKey('UserProfile', verbose_name="销售", related_name='customers', blank=True, null=True, )
    class_list = models.ManyToManyField('ClassList', verbose_name="已报班级", )

    def show_classes(self):
        return '|'.join([str(i) for i in self.class_list.all()])

    def show_status(self):
        color_dict = {
            'signed': 'green',
            'unregistered': 'red',
            'paid_in_full': 'yellow',
        }
        return '<span style="background-color: {};color: white;padding: 3px">{}</span>'.format(
            color_dict.get(self.status),
            self.get_status_display())

    def __str__(self):
        return self.name if self.name else self.qq


class Campuses(models.Model):
    """
    校区表
    """
    name = models.CharField(verbose_name='校区', max_length=64)
    address = models.CharField(verbose_name='详细地址', max_length=512, blank=True, null=True)

    def __str__(self):
        return self.name


class ClassList(models.Model):
    """
    班级表
    """
    course = models.CharField("课程名称", max_length=64, choices=course_choices)
    semester = models.IntegerField("学期")
    campuses = models.ForeignKey('Campuses', verbose_name="校区")
    price = models.IntegerField("学费", default=10000)
    memo = models.CharField('说明', blank=True, null=True, max_length=100)
    start_date = models.DateField("开班日期")
    graduate_date = models.DateField("结业日期", blank=True, null=True)
    teachers = models.ManyToManyField('UserProfile', verbose_name="老师")
    class_type = models.CharField(choices=class_type_choices, max_length=64, verbose_name='班额及类型', blank=True,
                                  null=True)

    class Meta:
        unique_together = ("course", "semester", 'campuses')

    def show_teacher(self):
        return "|".join([str(i) for i in self.teachers.all()])

    def __str__(self):
        return "{}{}({})".format(self.get_course_display(), self.semester, self.campuses)


class ConsultRecord(models.Model):
    """
    跟进记录表
    """
    customer = models.ForeignKey('Customer', verbose_name="所咨询客户")
    note = models.TextField(verbose_name="跟进内容...")
    status = models.CharField("跟进状态", max_length=8, choices=seek_status_choices, help_text="选择客户此时的状态")
    consultant = models.ForeignKey("UserProfile", verbose_name="跟进人", related_name='records')
    date = models.DateTimeField("跟进日期", auto_now_add=True)
    delete_status = models.BooleanField(verbose_name='删除状态', default=False)


class Enrollment(models.Model):
    """
    报名表
    """

    why_us = models.TextField("为什么报名", max_length=1024, default=None, blank=True, null=True)
    your_expectation = models.TextField("学完想达到的具体期望", max_length=1024, blank=True, null=True)
    contract_agreed = models.BooleanField("我已认真阅读完培训协议并同意全部协议内容", default=False)
    contract_approved = models.BooleanField("审批通过", help_text="在审阅完学员的资料无误后勾选此项,合同即生效", default=False)
    enrolled_date = models.DateTimeField(auto_now_add=True, verbose_name="报名日期")
    memo = models.TextField('备注', blank=True, null=True)
    delete_status = models.BooleanField(verbose_name='删除状态', default=False)
    customer = models.ForeignKey('Customer', verbose_name='客户名称')
    school = models.ForeignKey('Campuses')
    enrolment_class = models.ForeignKey("ClassList", verbose_name="所报班级")

    class Meta:
        unique_together = ('enrolment_class', 'customer')


class PaymentRecord(models.Model):
    """
    缴费记录表
    """
    pay_type = models.CharField("费用类型", choices=pay_type_choices, max_length=64, default="deposit")
    paid_fee = models.IntegerField("费用数额", default=0)
    note = models.TextField("备注", blank=True, null=True)
    date = models.DateTimeField("交款日期", auto_now_add=True)
    course = models.CharField("课程名", choices=course_choices, max_length=64, blank=True, null=True, default='N/A')
    class_type = models.CharField("班级类型", choices=class_type_choices, max_length=64, blank=True, null=True,
                                  default='N/A')
    enrolment_class = models.ForeignKey('ClassList', verbose_name='所报班级', blank=True, null=True)
    customer = models.ForeignKey('Customer', verbose_name="客户")
    consultant = models.ForeignKey('UserProfile', verbose_name="销售")
    delete_status = models.BooleanField(verbose_name='删除状态', default=False)

    status_choices = (
        (1, '未审核'),
        (2, '已审核'),
    )
    status = models.IntegerField(verbose_name='审核', default=1, choices=status_choices)

    confirm_date = models.DateTimeField(verbose_name="确认日期", null=True, blank=True)
    confirm_user = models.ForeignKey(verbose_name="确认人", to='UserProfile', related_name='confirms', null=True,
                                     blank=True)


class CourseRecord(models.Model):
    """课程记录表"""
    day_num = models.IntegerField("节次", help_text="此处填写第几节课或第几天课程...,必须为数字")
    date = models.DateField(auto_now_add=True, verbose_name="上课日期")
    course_title = models.CharField('本节课程标题', max_length=64, blank=True, null=True)
    course_memo = models.TextField('本节课程内容', max_length=300, blank=True, null=True)
    has_homework = models.BooleanField(default=True, verbose_name="本节有作业")
    homework_title = models.CharField('本节作业标题', max_length=64, blank=True, null=True)
    homework_memo = models.TextField('作业描述', max_length=500, blank=True, null=True)
    scoring_point = models.TextField('得分点', max_length=300, blank=True, null=True)
    re_class = models.ForeignKey('ClassList', verbose_name="班级")
    teacher = models.ForeignKey('UserProfile', verbose_name="讲师")

    class Meta:
        unique_together = ('re_class', 'day_num')


class StudyRecord(models.Model):
    """

app1/views/account.py
from django.shortcuts import render, redirect, reverse
from app1 import models
from app1.forms import ReForm
import hashlib
from rbec.service.permission import init_permisson


# 登录
def login(request):
    err_msg = ''
    if request.method == 'POST':
        # 获取提交的数据
        user = request.POST.get('user')
        pwd = request.POST.get('pwd')
        print(user)
        print(pwd)
        # 对密码进行加密
        md5 = hashlib.md5()
        md5.update(pwd.encode('utf-8'))
        pwd = md5.hexdigest()
        # 按照输入账户密码从数据库中查找
        obj = models.UserProfile.objects.filter(username=user, password=pwd, is_active=True).first()

        if obj:
            # 认证成功 保存用户的id在session中
            request.session['user_id'] = obj.pk
            init_permisson(request, obj)
            print('obj', obj)
            # 跳转到首页
            return redirect('/app1/customer_list/')
        err_msg = '用户名或密码错误'
    return render(request, 'login.html', {'err_msg': err_msg})


# 清除session, .flush()删除cookie和session, .delete()不删除cookie
def logout(request):
    request.session.flush()
    return redirect(reverse('login'))


# 注册
def reg(request):
    form_obj = ReForm()  # form表单校验之后的结果
    if request.method == 'POST':
        form_obj = ReForm(request.POST)  # 把 POST 请求放入到form 验证
        if form_obj.is_valid():  # 如果通过验证
            form_obj.save()  # 保存数据
            return redirect('/login/')  # 重定向,返回登录界面
    return render(request, 'reg.html', {'form_obj': form_obj})

app1/templates/consultant/consult_add.html
{% extends 'layout.html' %}

{% block content %}
    <div style="margin: 15px">

        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">添加跟进记录</h3>
            </div>
            <div class="panel-body">
                <form class="form-horizontal" method="post" action="" novalidate>
                    {% csrf_token %}

                    {% for field in form_obj %}
                        <div class="form-group {% if field.errors %}has-error{% endif %} ">
                            <label for="{{ field.id_for_label }}"
                                   class="col-sm-2 control-label">{{ field.label }}</label>
                            <div class="col-sm-8">
                                {{ field }}
                                <span class="help-block">{{ field.errors.0 }}</span>
                            </div>
                        </div>
                    {% endfor %}

                    <div class="form-group">
                        <div class="col-sm-offset-2 col-sm-10">
                            <button type="submit" class="btn btn-default">提交</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>


{% endblock %}

app1/templates/consultant/consult_edit.html
{% extends 'layout.html' %}

{% block content %}
    <div style="margin: 15px">

        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">编辑跟进记录</h3>
            </div>
            <div class="panel-body">
                <form class="form-horizontal" method="post" action="" novalidate>
                    {% csrf_token %}

                    {% for field in form_obj %}
                        <div class="form-group {% if field.errors %}has-error{% endif %} ">
                            <label for="{{ field.id_for_label }}"
                                   class="col-sm-2 control-label">{{ field.label }}</label>
                            <div class="col-sm-8">
                                {{ field }}
                                <span class="help-block">{{ field.errors.0 }}</span>
                            </div>
                        </div>
                    {% endfor %}

                    <div class="form-group">
                        <div class="col-sm-offset-2 col-sm-10">
                            <button type="submit" class="btn btn-default">提交</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>


{% endblock %}

app1/templates/consultant/consult_list.html
{% extends 'layout.html' %}
{% block content %}
    <div style="margin: 15px">
        <a href="{% url 'consult_add' %}" class="btn btn-primary btn-sm">添加</a>
        <table class="table table-hover table-bordered">
            <thead>
            <tr>
                <th>序号</th>
                <th>客户</th>
                <th>状态</th>
                <th>跟进日期</th>
                <th>跟进内容</th>
                <th>跟进人</th>
                <th>操作</th>
            </tr>
            </thead>
            <tbody>
            {% for consult in all_consult %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ consult.customer }}</td>
                    <td>{{ consult.status }}</td>
                    <td>{{ consult.date }}</td>
                    <td>{{ consult.note }}</td>
                    <td>{{ consult.consultant }}</td>
                    <td>
                        <a href="{% url 'consult_edit' consult.pk %}">
                            <i class="fa fa-pencil-square-o"></i>
                        </a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>

{% endblock %}

app1/templates/consultant/customer_add.html
{% extends 'layout.html' %}

{% block content %}
    <div style="margin: 15px">

        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">添加客户</h3>
            </div>
            <div class="panel-body">
                <form class="form-horizontal" method="post" action="" novalidate>
                    {% csrf_token %}

                    {% for field in form_obj %}
                        <div class="form-group {% if field.errors %}has-error{% endif %} ">
                            <label for="{{ field.id_for_label }}"
                                   class="col-sm-2 control-label">{{ field.label }}</label>
                            <div class="col-sm-8">
                                {{ field }}
                                <span class="help-block">{{ field.errors.0 }}</span>
                            </div>
                        </div>
                    {% endfor %}



                    <div class="form-group">
                        <div class="col-sm-offset-2 col-sm-10">
                            <button type="submit" class="btn btn-default">提交</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>


{% endblock %}

app1/templates/consultant/customer_change.html
{% extends 'layout.html' %}

{% block content %}
    <div style="margin: 15px">

        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">
                    {% if edit_id %}
                        编辑客户
                    {% else %}
                        新增客户
                    {% endif %}

                </h3>
            </div>
            <div class="panel-body">
                <form class="form-horizontal" method="post" action="" novalidate>
                    {% csrf_token %}

                    {% for field in form_obj %}
                        <div class="form-group {% if field.errors %}has-error{% endif %} ">
                            <label for="{{ field.id_for_label }}"
                                   class="col-sm-2 control-label">{{ field.label }}</label>
                            <div class="col-sm-8">
                                {{ field }}
                                <span class="help-block">{{ field.errors.0 }}</span>
                            </div>
                        </div>
                    {% endfor %}



                    <div class="form-group">
                        <div class="col-sm-offset-2 col-sm-10">
                            <button type="submit" class="btn btn-default">提交</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>


{% endblock %}

app1/templates/consultant/customer_edit.html
{% extends 'layout.html' %}

{% block content %}
    <div style="margin: 15px">

        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">编辑客户</h3>
            </div>
            <div class="panel-body">
                <form class="form-horizontal" method="post" action="" novalidate>
                    {% csrf_token %}

                    {% for field in form_obj %}
                        <div class="form-group {% if field.errors %}has-error{% endif %} ">
                            <label for="{{ field.id_for_label }}"
                                   class="col-sm-2 control-label">{{ field.label }}</label>
                            <div class="col-sm-8">
                                {{ field }}
                                <span class="help-block">{{ field.errors.0 }}</span>
                            </div>
                        </div>
                    {% endfor %}



                    <div class="form-group">
                        <div class="col-sm-offset-2 col-sm-10">
                            <button type="submit" class="btn btn-default">提交</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>


{% endblock %}

app1/templates/consultant/customer_list.html
{% extends 'layout.html' %}
{% block content %}
    <div style="margin: 15px">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">客户展示</h3>
            </div>
            <div class="panel-body">
                <div>
                    <a class="btn btn-sm btn-primary" href="{% url 'customer_add' %}">添加</a>
                </div>
                <form action="" class="form-inline pull-right">
                    <input type="text" class="form-control" name="query">
                    <button class="btn btn-sm btn-primary">搜索</button>
                </form>

                <form action="" method="post" class="form-inline">
                    {% csrf_token %}
                    <select name="action" id="" class="form-control">
                        <option value="">选择</option>
                        <option value="multi_apply">转成私户</option>
                        <option value="multi_public">转成公户</option>
                        <option value="multi_delete">批量删除</option>
                    </select>
                    <button class="btn btn-sm btn-primary">提交</button>
                    <table class="table table-bordered table-hover">
                        <thead>
                        <tr>
                            <th>选择</th>
                            <th>序号</th>
                            <th>QQ</th>
                            <th>姓名</th>
                            <th>性别</th>
                            <th>出生日期</th>
                            <th>客户来源</th>
                            <th>咨询课程</th>
                            <th>状态</th>
                            <th>咨询日期</th>
                            <th>销售</th>
                            <th>已报班级</th>
                            <th>操作</th>
                        </tr>
                        </thead>

                        <tbody>
                        {% for i in all_customer %}
                            <tr>
                                <td><input type="checkbox" name="id" value="{{ i.pk }}"></td>
                                <td>{{ forloop.counter }}</td>
                                <td>{{ i.qq }}</td>
                                <td>{{ i.name|default:'-' }}</td>
                                <td>{{ i.get_sex_display }}</td>
                                <td>{{ i.birthday }}</td>
                                <td>{{ i.get_source_display }}</td>
                                <td>{{ i.course }}</td>
                                <td>{{ i.show_status|safe }}</td>
                                <td>{{ i.date }}</td>
                                <td>{{ i.consultant.name }}</td>
                                <td>{{ i.show_classes }}</td>
                                <td><a
                                        href="{% url 'customer_edit' i.pk %}"><i
                                        class="fa fa-pencil-square-o"></i></a></td>
                            </tr>
                        {% endfor %}
                        </tbody>

                    </table>
                </form>

                <nav aria-label="Page navigation">
                    <ul class="pagination">
                        {{ page_html|safe }}
                    </ul>
                </nav>

            </div>
        </div>


    </div>

{% endblock %}

app1/templates/consultant/enrollment.html
{% extends 'layout.html' %}

{% block content %}
    <div style="margin: 15px">

        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">{{ title }}</h3>
            </div>
            <div class="panel-body">
                <form class="form-horizontal" method="post" action="" novalidate>
                    {% csrf_token %}

                    {% for field in form_obj %}
                        <div class="form-group {% if field.errors %}has-error{% endif %} ">
                            <label for="{{ field.id_for_label }}"
                                   class="col-sm-2 control-label">{{ field.label }}</label>
                            <div class="col-sm-8">
                                {{ field }}
                                <span class="help-block">{{ field.errors.0 }}</span>
                            </div>
                        </div>
                    {% endfor %}

                    <div class="form-group">
                        <div class="col-sm-offset-2 col-sm-10">
                            <button type="submit" class="btn btn-default">提交</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>


{% endblock %}

app1/templates/consultant/enrollment_list.html
{% extends 'layout.html' %}

{% block content %}
    <div style="margin: 15px;">
        <a href="{% url 'enrollment_add' '0' %}" class="btn btn-primary btn-sm">添加</a>
        <table class="table table-hover table-bordered">

            <thrad>
                <tr>
                    <th>序号</th>
                    <th>报名原因</th>
                    <th>期望</th>
                    <th>审核</th>
                    <th>报名日期</th>
                    <th>客户</th>
                    <th>班级</th>
                    <th>操作</th>
                </tr>
            </thrad>
            <tbody>
            {% for enrollment in all_enrollment %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ enrollment.why_us }}</td>
                    <td>{{ enrollment.your_expectation }}</td>
                    <td>{{ enrollment.contract_approved }}</td>
                    <td>{{ enrollment.enrolled_date }}</td>
                    <td>{{ enrollment.customer }}</td>
                    <td>{{ enrollment.enrolment_class }}</td>

                    <td>
                        <a href="{% url 'enrollment_edit' enrollment.pk %}"> <i class="fa fa-pencil-square-o"></i> </a>
                    </td>
                </tr>
            {% endfor %}


            </tbody>
        </table>
    </div>

{% endblock %}